blank_issues_enabled: false
contact_links:
  - name: Contributing guide
    url: https://github.com/orwa-mahmoud/sight/blob/main/CONTRIBUTING.md
  - name: Documentation
    url: https://github.com/orwa-mahmoud/sight/blob/main/README.md#documentation
