"""add is_platform_admin to users

Revision ID: 0bdc78f0ee44
Revises: 7fefd96ee761
Create Date: 2026-06-02 12:18:31.306925

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bdc78f0ee44"
down_revision: str | Sequence[str] | None = "7fefd96ee761"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_platform_admin", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_platform_admin")
    # ### end Alembic commands ###
