"""add contacts and telegram_phones tables, remove asker fields from questions

Revision ID: 231b816fb031
Revises: cd1f6f375fb6
Create Date: 2026-05-25 20:44:58.096363

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "231b816fb031"
down_revision: str | Sequence[str] | None = "cd1f6f375fb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_phones",
        sa.Column("telegram_user_id", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telegram_user_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "phone", name="uq_contacts_tenant_phone"),
    )
    op.create_index(op.f("ix_contacts_phone"), "contacts", ["phone"], unique=False)
    op.create_index(op.f("ix_contacts_telegram_user_id"), "contacts", ["telegram_user_id"], unique=False)
    op.create_index(op.f("ix_contacts_tenant_id"), "contacts", ["tenant_id"], unique=False)
    op.add_column("questions", sa.Column("contact_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_questions_contact_id"), "questions", ["contact_id"], unique=False)
    op.create_foreign_key(None, "questions", "contacts", ["contact_id"], ["id"], ondelete="SET NULL")
    op.drop_column("questions", "asker_contact")
    op.drop_column("questions", "asker_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("asker_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column("questions", sa.Column("asker_contact", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_index(op.f("ix_questions_contact_id"), table_name="questions")
    op.drop_column("questions", "contact_id")
    op.drop_index(op.f("ix_contacts_tenant_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_telegram_user_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_phone"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("telegram_phones")
    # ### end Alembic commands ###
