"""add FK from conversations.participant_id to contacts.id

Revision ID: 270663abb89c
Revises: 47bc4badd4da
Create Date: 2026-05-25 22:20:56.053762

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "270663abb89c"
down_revision: str | Sequence[str] | None = "47bc4badd4da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "conversations", "contacts", ["participant_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversations", type_="foreignkey")
    # ### end Alembic commands ###
