"""add provider_message_id to messages for durable webhook dedup

Revision ID: 3288c2fdca2d
Revises: c1a619c45aaf
Create Date: 2026-06-14 22:18:40.946466

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3288c2fdca2d"
down_revision: str | Sequence[str] | None = "c1a619c45aaf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("provider_message_id", sa.String(length=128), nullable=True))
    op.create_index(
        "uq_messages_conversation_provider_msg",
        "messages",
        ["conversation_id", "provider_message_id"],
        unique=True,
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_messages_conversation_provider_msg",
        table_name="messages",
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.drop_column("messages", "provider_message_id")
    # ### end Alembic commands ###
