"""key_facts participant_identifier to contact_id FK

Revision ID: 47bc4badd4da
Revises: 231b816fb031
Create Date: 2026-05-25 22:02:40.252294

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47bc4badd4da"
down_revision: str | Sequence[str] | None = "231b816fb031"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("key_facts", sa.Column("contact_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("ix_key_facts_participant_identifier"), table_name="key_facts")
    op.drop_constraint(op.f("uq_key_fact_per_participant"), "key_facts", type_="unique")
    op.create_index(op.f("ix_key_facts_contact_id"), "key_facts", ["contact_id"], unique=False)
    op.create_unique_constraint("uq_key_fact_per_contact", "key_facts", ["tenant_id", "contact_id", "key"])
    op.create_foreign_key(None, "key_facts", "contacts", ["contact_id"], ["id"], ondelete="CASCADE")
    op.drop_column("key_facts", "participant_identifier")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "key_facts", sa.Column("participant_identifier", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "key_facts", type_="foreignkey")
    op.drop_constraint("uq_key_fact_per_contact", "key_facts", type_="unique")
    op.drop_index(op.f("ix_key_facts_contact_id"), table_name="key_facts")
    op.create_unique_constraint(
        op.f("uq_key_fact_per_participant"),
        "key_facts",
        ["tenant_id", "participant_identifier", "key"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_key_facts_participant_identifier"), "key_facts", ["participant_identifier"], unique=False)
    op.drop_column("key_facts", "contact_id")
    # ### end Alembic commands ###
