"""add key_facts table

Revision ID: 72d0ce6fb73e
Revises: b969d424a7c7
Create Date: 2026-05-25 11:00:59.055857

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "72d0ce6fb73e"
down_revision: str | Sequence[str] | None = "b969d424a7c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "key_facts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("participant_identifier", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "participant_identifier", "key", name="uq_key_fact_per_participant"),
    )
    op.create_index(op.f("ix_key_facts_participant_identifier"), "key_facts", ["participant_identifier"], unique=False)
    op.create_index(op.f("ix_key_facts_tenant_id"), "key_facts", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_key_facts_tenant_id"), table_name="key_facts")
    op.drop_index(op.f("ix_key_facts_participant_identifier"), table_name="key_facts")
    op.drop_table("key_facts")
    # ### end Alembic commands ###
