"""drop_embedding_dimensions_from_tenant_configs

Revision ID: 9316e604f4a6
Revises: f5c452deacee
Create Date: 2026-05-26 14:01:28.147881

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9316e604f4a6"
down_revision: str | Sequence[str] | None = "f5c452deacee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_configs", "embedding_dimensions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant_configs", sa.Column("embedding_dimensions", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
