"""add tenant_configs table

Revision ID: b969d424a7c7
Revises: 56d48d3143be
Create Date: 2026-05-24 23:40:47.368709

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b969d424a7c7"
down_revision: str | Sequence[str] | None = "56d48d3143be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("llm_provider", sa.String(length=32), nullable=False),
        sa.Column("llm_model", sa.String(length=64), nullable=False),
        sa.Column("llm_api_key", sa.Text(), nullable=False),
        sa.Column("llm_max_tokens", sa.Integer(), nullable=False),
        sa.Column("llm_temperature", sa.Float(), nullable=False),
        sa.Column("embedding_provider", sa.String(length=32), nullable=False),
        sa.Column("embedding_model", sa.String(length=64), nullable=False),
        sa.Column("embedding_api_key", sa.Text(), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("whatsapp_phone_number_id", sa.String(length=64), nullable=True),
        sa.Column("whatsapp_access_token", sa.Text(), nullable=True),
        sa.Column("whatsapp_verify_token", sa.String(length=255), nullable=True),
        sa.Column("telegram_bot_token", sa.Text(), nullable=True),
        sa.Column("telegram_webhook_secret", sa.String(length=255), nullable=True),
        sa.Column("bot_name", sa.String(length=255), nullable=False),
        sa.Column("bot_welcome_message", sa.Text(), nullable=False),
        sa.Column("bot_language", sa.String(length=8), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", name="uq_tenant_config_tenant"),
    )
    op.create_index(op.f("ix_tenant_configs_tenant_id"), "tenant_configs", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenant_configs_tenant_id"), table_name="tenant_configs")
    op.drop_table("tenant_configs")
    # ### end Alembic commands ###
