"""add_whatsapp_app_secret_to_tenant_configs

Revision ID: f5c452deacee
Revises: 270663abb89c
Create Date: 2026-05-26 00:27:53.063216

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5c452deacee"
down_revision: str | Sequence[str] | None = "270663abb89c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenant_configs", sa.Column("whatsapp_app_secret", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_configs", "whatsapp_app_secret")
    # ### end Alembic commands ###
